### ISSUE TITLE
pgap.py --update spits out python traceback

### ISSUE THREAD

**Issue by tseemann** [ncbi/pgap#12]
I followed the instructions:
```
wget ....
chmod +x pgap.py
pgap.py --update
```
And I get this:

```
The latest version of PGAP is 2019-05-13.build3740, you have nothing installed >
Downloading (as needed) Docker image ncbi/pgap:2019-05-13.build3740
Traceback (most recent call last):
  File "./pgap.py", line 387, in install_docker
    r = subprocess.run([self.dockercmd, 'pull', self.docker_image], check=True)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/subprocess>    with Popen(*popenargs, **kwargs) as process:
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/subprocess>
    restore_signals, start_new_session)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/subprocess>
    executable = os.fsencode(executable)
  File "/home/linuxbrew/.linuxbrew/bin/../Cellar/python/3.7.3/lib/python3.7/os.>
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pgap.py", line 475, in <module>
    main()
  File "./pgap.py", line 465, in main
    params = Setup(args)
  File "./pgap.py", line 267, in __init__
    self.update()
  File "./pgap.py", line 378, in update
    self.install_docker()
  File "./pgap.py", line 389, in install_docker
    except CalledProcessError:
```

**Comment by slottad** [comment]
It looks like Docker is not in your path.
Sorry for the poor error message, we can do a better job with that feedback.

You should be able to successfully execute:

  $ docker run hello-world

From the same command line. Once you are able to do that, pgap.py should work.

**Comment by tseemann** [comment]
Ok, yes I do not have `docker` installed on that machine. 
I'll leave this issue open for the improvement of the error reporting.

**Comment by whlavina** [comment]
The fix to avoid the stack trace (except in debug mode) has been committed to the master branch, and is in testing. I'm closing this ticket; feel free to re-open if there are remaining issues.
