### ISSUE TITLE
WARNING Final process status is permanentFail

### ISSUE THREAD

**Issue by Ahmer1122** [ncbi/pgap#242]
[errorCWLtool.txt](https://github.com/ncbi/pgap/files/10472161/errorCWLtool.txt)
![Screenshot from 2023-01-21 13-27-52](https://user-images.githubusercontent.com/98017313/213866852-ec0cf98c-cdc7-4718-8c74-0ce869cfd1a9.png)
[submol.txt](https://github.com/ncbi/pgap/files/10472168/submol.txt)
Hello, I am trying to run the PGAP pipeline with a submol.yaml file for genebank submission. I am facing the Permanentfail issue. I have tried all of the previous suggestions from issue #239. However, this time non of the solution is working. 
debug folder consists of many folders. 
CWL and submol.yaml files are attached.

**Comment by azat-badretdin** [comment]
Thank you for your question, Ahmer!

Your log file says

```
[2023-01-21 12:03:06] INFO [job yaml2json] /pgap/output/debug/tmp-outdir/0u97lw5r$ yaml2json.py \
    /pgap/output/debug/tmpdir/mrcybsn2/stg7d2b2552-fd1d-4bc0-860a-32dab347571d/pgap_submol_lecv8d8d.yaml \
    submol.json
Traceback (most recent call last):
  File "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/yaml2json.py", line 15, in <module>
    y=yaml.safe_load(inFile.read())
  File "/root/venv/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/root/venv/lib/python3.9/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/root/venv/lib/python3.9/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/root/venv/lib/python3.9/site-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/root/venv/lib/python3.9/site-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0082: special characters are not allowed
  in "<unicode string>", position 603
[2023-01-21 12:03:06] DEBUG Could not collect memory usage, job ended before monitoring began.
```

Unfortunately you hit the area we are little bit behind - "strange" characters in names. 

This time it's a Polish character "ł" in "Pełka" 

The workaround is to replace it temporary with "l" and ask GenBank to fix it back to proper character upon acceptance of submission. 

Hope this works!

**Comment by Ahmer1122** [comment]
Dear Sir, Thank you very much.

Best regards,

Ahmer

**Comment by azat-badretdin** [comment]
I am very glad it helped!
