### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by dlhuseby29** [ncbi/pgap#247]
Since updating to the latest version of pgap, we have been unable to complete an annotation run without errors. The process appears to finish, as judged by generating a .gbk file, but it does spit out a number of error messages. Looking at the log file, we can find the first permanentFail message seems to be associated with checkm.  Checkm, as far as we can tell, is working as judged by running it by itself on its own test data. Checkm was not a part of the version of pgap that we previously had working correctly (Build 5508).

Since we have had this problem, we've tried to re-run the test genome many times and no matter how we have tried to change various parameters, always seems to generate these errors.

Running on:
Mac Pro with OS 10.13.6
pgap.py build 6494
Docker version 20.10.8
(We generate the same error on a newer Mac Pro running OS 12.6.3, pgap.py build 6494, Docker version 20.10.23)

[Debug Logs.zip](https://github.com/ncbi/pgap/files/10958728/Debug.Logs.zip)
[cwltool.log.zip](https://github.com/ncbi/pgap/files/10958735/cwltool.log.zip)

Any suggestions would be appreciated!

**Comment by azat-badretdin** [comment]
Thank you for your report! 

For starters, could you please post some of these error messages that bother you?

Also: most likely, you are fine since you got your annotation.

**Comment by dlhuseby29** [comment]
Hello,

Thank you for your reply. 

The output is extensive. The screen looks like it puts out a similar set of information as the cwltool.log, which is this case is 25 mb of text.

We may have complicated matters further; in trying to fix this we noticed that there were some python errors popping up, so we updated python. Now we get essentially the same errors, but now we do not get a .gbk file as an output, only a .gff file.

Searching for the first occurrence of a permanentfail and tracking backward a bit reveals the following large section of text where the problems seem to be originating from:


+ grep -Pq 'domain\tBacteria\t' /tmp/p1rybzqw/stg1eeed899-1800-40e6-89be-63b2a2a86e9f/checkm/taxon_marker_sets.tsv
+ set +e
+ /root/venv/bin/checkm taxonomy_wf -t 1 -g -x fa domain Bacteria bins-prot/ taxonomy_wf-prot/
Process SyncManager-1:
Traceback (most recent call last):
  File "/opt/python-3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/managers.py", line 583, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/managers.py", line 156, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/root/venv/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/root/venv/lib/python3.9/site-packages/checkm/main.py", line 992, in parseOptions
    self.analyze(options)
  File "/root/venv/lib/python3.9/site-packages/checkm/main.py", line 326, in analyze
    binIdToModels = mgf.find(binFiles,
  File "/root/venv/lib/python3.9/site-packages/checkm/markerGeneFinder.py", line 68, in find
    binIdToModels = mp.Manager().dict()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
+ taxonomy_wf_error_code=1
+ set -e
+ [[ 1 -ne 0 ]]
+ continue
+ [[ 1 -eq 0 ]]
/CERR

Error: (CFileException::eFileIO) Error opening checkm dombtblout: /tmp/izql0mp0/checkm.242201698190784wDcQrZ/fasta_by_scaffold/checkm.out;     Stack trace:;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x4134fd;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x4114ce;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x412406;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libgpxlib.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_worker_thread.cpp:274 ncbi::CWorkerThread::x_DoJob(ncbi::CRef<ncbi::objects::CGPX_Job, ncbi::CObjectCounterLocker>, ncbi::CDiagContext&) offset=0x0 addr=0x7f1e64ab96c8;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libgpxlib.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_worker_thread.cpp:477 ncbi::CParallelWorkerThread::Main() offset=0x0 addr=0x7f1e64abb068;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbithr.cpp:578 ncbi::CThread::Wrapper(void*) offset=0x0 addr=0x7f1e4ba6174f;      /usr/lib64/libpthread-2.17.so :0  offset=0x0 addr=0x7f1e5613dea4;      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7f1e4a471b0c;       :0  offset=0x0 addr=0xffffffffffffffff;
Error: Error calling ProcessCheckMResults block: (CFileException::eFileIO) Error opening checkm dombtblout: /tmp/izql0mp0/checkm.242201698190784wDcQrZ/fasta_by_scaffold/checkm.out
Error: (CFileException::eFileIO) Error opening checkm dombtblout: /tmp/izql0mp0/checkm.242201698190784wDcQrZ/fasta_by_scaffold/checkm.out;     Stack trace:;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x4134fd;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x4114ce;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x412406;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libgpxlib.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_worker_thread.cpp:274 ncbi::CWorkerThread::x_DoJob(ncbi::CRef<ncbi::objects::CGPX_Job, ncbi::CObjectCounterLocker>, ncbi::CDiagContext&) offset=0x0 addr=0x7f1e64ab96c8;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libgpxlib.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_worker_thread.cpp:477 ncbi::CParallelWorkerThread::Main() offset=0x0 addr=0x7f1e64abb068;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbithr.cpp:578 ncbi::CThread::Wrapper(void*) offset=0x0 addr=0x7f1e4ba6174f;      /usr/lib64/libpthread-2.17.so :0  offset=0x0 addr=0x7f1e5613dea4;      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7f1e4a471b0c;       :0  offset=0x0 addr=0xffffffffffffffff;
Error: Error in the body of Process: (CFileException::eFileIO) Error opening checkm dombtblout: /tmp/izql0mp0/checkm.242201698190784wDcQrZ/fasta_by_scaffold/checkm.out
Error: (CFileException::eFileIO) Error opening checkm dombtblout: /tmp/izql0mp0/checkm.242201698190784wDcQrZ/fasta_by_scaffold/checkm.out;     Stack trace:;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x4134fd;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x4114ce;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x412406;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libgpxlib.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_worker_thread.cpp:274 ncbi::CWorkerThread::x_DoJob(ncbi::CRef<ncbi::objects::CGPX_Job, ncbi::CObjectCounterLocker>, ncbi::CDiagContext&) offset=0x0 addr=0x7f1e64ab96c8;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libgpxlib.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_worker_thread.cpp:477 ncbi::CParallelWorkerThread::Main() offset=0x0 addr=0x7f1e64abb068;      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbithr.cpp:578 ncbi::CThread::Wrapper(void*) offset=0x0 addr=0x7f1e4ba6174f;      /usr/lib64/libpthread-2.17.so :0  offset=0x0 addr=0x7f1e5613dea4;      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7f1e4a471b0c;       :0  offset=0x0 addr=0xffffffffffffffff;
Error: error processing job: (CFileException::eFileIO) Error opening checkm dombtblout: /tmp/izql0mp0/checkm.242201698190784wDcQrZ/fasta_by_scaffold/checkm.out
terminate called after throwing an instance of 'ncbi::CException'
  what():  NCBI C++ Exception:
    Error: LIB(CException::eUnknown) "/export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_app.cpp", line 411: ncbi::CGPX_WorkerApp::Run() --- 1 jobs failed
     Stack trace:
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libgpxlib.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_app.cpp:409 ncbi::CGPX_WorkerApp::Run() offset=0x0 addr=0x7f1e64acbc09
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x41a540
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp:702 ncbi::CNcbiApplicationAPI::x_TryMain(ncbi::EAppDiagStream, char const*, int*, bool*) offset=0x0 addr=0x7f1e4b969472
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp:1014 ncbi::CNcbiApplicationAPI::AppMain(int, char const* const*, char const* const*, ncbi::EAppDiagStream, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7f1e4b96ca3c
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x40be52
      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7f1e4a395554
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode :0  offset=0x0 addr=0x40c029
       :0  offset=0x0 addr=0xffffffffffffffff

Stack trace (most recent call last):
#13   Object "", at 0xffffffffffffffff, in 
#12   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode", at 0x40c029, in _start
#11   Object "/usr/lib64/libc-2.17.so", at 0x7f1e4a395554, in __libc_start_main
#10   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode", at 0x40be52, in main
#9    Source "/export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp", line 1014, in AppMain [0x7f1e4b96ca3c]
#8    Source "/export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp", line 702, in x_TryMain [0x7f1e4b969472]
#7    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2022-12-13.build6494/arch/x86_64/bin/checkm_wnode", at 0x41a540, in ncbi::CCCheckMWNodeApp::Run()
#6    Source "/export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/gpexec/queue/lib/wn_app.cpp", line 409, in Run [0x7f1e64acbc5a]
#5    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_throw.cc", line 93, in __cxa_throw [0x7f1e4af17222]
#4    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 57, in terminate [0x7f1e4af16fe0]
#3    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 47, in __cxa_begin_catch [0x7f1e4af16f95]
#2    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/vterminate.cc", line 95, in __verbose_terminate_handler [0x7f1e4af191a4]
#1    Object "/usr/lib64/libc-2.17.so", at 0x7f1e4a3aaa77, in abort
#0    Object "/usr/lib64/libc-2.17.so", at 0x7f1e4a3a9387, in raise
Aborted (Signal sent by tkill() 2422 501)
[2023-03-14 08:53:48] INFO [job checkm_wnode] Max memory used: 31MiB
[2023-03-14 08:53:48] WARNING [job checkm_wnode] was terminated by signal: SIGABRT
[2023-03-14 08:53:48] WARNING [job checkm_wnode] completed permanentFail
[2023-03-14 08:53:48] DEBUG [job checkm_wnode] outputs {
    "outdir": {
        "location": "file:///tmp/qk6mf4gi/output",
        "basename": "output",
        "nameroot": "output",
        "nameext": "",
        "class": "Directory"
    }
}
[2023-03-14 08:53:48] DEBUG [step checkm_wnode] produced output {
    "file:///pgap/pgap/task_types/tt_checkm_wnode.cwl#checkm_wnode/outdir": {
        "location": "file:///tmp/qk6mf4gi/output",
        "basename": "output",
        "nameroot": "output",
        "nameext": "",
        "class": "Directory"
    }
}
[2023-03-14 08:53:48] WARNING [step checkm_wnode] completed permanentFail
[2023-03-14 08:53:48] DEBUG [job checkm_wnode] Removing input staging directory /tmp/p1rybzqw
[2023-03-14 08:53:48] DEBUG [job checkm_wnode] Removing temporary directory /tmp/izql0mp0
[2023-03-14 08:53:48] INFO [workflow run_checkm] completed permanentFail
[2023-03-14 08:53:48] DEBUG [workflow run_checkm] outputs {
    "checkm_raw": null,
    "checkm_results": null
}
[2023-03-14 08:53:48] DEBUG [step run_checkm] produced output {
    "file:///pgap/pgap/checkm/wf_checkm.cwl#run_checkm/checkm_raw": null,
    "file:///pgap/pgap/checkm/wf_checkm.cwl#run_checkm/checkm_results": null
}
[2023-03-14 08:53:48] WARNING [step run_checkm] completed permanentFail
[2023-03-14 08:53:48] INFO [workflow checkm] completed permanentFail
[2023-03-14 08:53:48] DEBUG [workflow checkm] outputs {
    "checkm_raw": null,
    "checkm_results": null
}
[2023-03-14 08:53:48] DEBUG [step checkm] produced output {
    "file:///pgap/pgap/wf_common.cwl#checkm/checkm_raw": null,
    "file:///pgap/pgap/wf_common.cwl#checkm/checkm_results": null
}
[2023-03-14 08:53:48] WARNING [step checkm] completed permanentFail
[2023-03-14 08:53:48] INFO [workflow standard_pgap] completed permanentFail
[2023-03-14 08:53:48] DEBUG [workflow standard_pgap] outputs {
    "cds_nucleotide_fasta": null,
    "cds_protein_fasta": null,
    "checkm_raw": null,
    "checkm_results": null,
    "final_asndisc_error_diag": null,
    "final_asnval_error_diag": null,
    "gbent": null,
    "gbk": null,
    "gff": {
        "location": "file:///tmp/k4xon_hf/annot.gff",
        "basename": "annot.gff",
        "nameroot": "annot",
        "nameext": ".gff",
        "class": "File",
        "checksum": "sha1$f4ec46edc1105e02cae1ef65f912d335eac9aa8e",
        "size": 298069,
        "http://commonwl.org/cwltool#generation": 0
    },
    "gff_enhanced": null,
    "initial_asndisc_error_diag": {
        "location": "file:///tmp/a1y2c7sf/initial_asndisc_diag.xml",
        "basename": "initial_asndisc_diag.xml",
        "nameroot": "initial_asndisc_diag",
        "nameext": ".xml",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    },
    "initial_asnval_error_diag": {
        "location": "file:///tmp/mrllf3lb/initial_asnval_diag.xml",
        "basename": "initial_asnval_diag.xml",
        "nameroot": "initial_asnval_diag",
        "nameext": ".xml",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    },
    "nucleotide_fasta": null,
    "proc_annot_stats": {
        "location": "file:///tmp/o5efg8rq/var_proc_annot_stats.xml",
        "basename": "var_proc_annot_stats.xml",
        "nameroot": "var_proc_annot_stats",
        "nameext": ".xml",
        "class": "File",
        "checksum": "sha1$003481cdfe43aed0344f280719a7300decb3e3dc",
        "size": 25542,
        "http://commonwl.org/cwltool#generation": 0
    },
    "protein_fasta": null,
    "sqn": null
}
[2023-03-14 08:53:48] DEBUG [step standard_pgap] produced output {
    "file:///pgap/pgap/pgap.cwl#standard_pgap/gbent": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/gbk": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/gff": {
        "location": "file:///tmp/k4xon_hf/annot.gff",
        "basename": "annot.gff",
        "nameroot": "annot",
        "nameext": ".gff",
        "class": "File",
        "checksum": "sha1$f4ec46edc1105e02cae1ef65f912d335eac9aa8e",
        "size": 298069,
        "http://commonwl.org/cwltool#generation": 0
    },
    "file:///pgap/pgap/pgap.cwl#standard_pgap/gff_enhanced": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/nucleotide_fasta": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/protein_fasta": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/cds_nucleotide_fasta": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/cds_protein_fasta": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/sqn": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/initial_asndisc_error_diag": {
        "location": "file:///tmp/a1y2c7sf/initial_asndisc_diag.xml",
        "basename": "initial_asndisc_diag.xml",
        "nameroot": "initial_asndisc_diag",
        "nameext": ".xml",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    },
    "file:///pgap/pgap/pgap.cwl#standard_pgap/initial_asnval_error_diag": {
        "location": "file:///tmp/mrllf3lb/initial_asnval_diag.xml",
        "basename": "initial_asnval_diag.xml",
        "nameroot": "initial_asnval_diag",
        "nameext": ".xml",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    },
    "file:///pgap/pgap/pgap.cwl#standard_pgap/final_asndisc_error_diag": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/final_asnval_error_diag": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/checkm_raw": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/checkm_results": null
}
[2023-03-14 08:53:48] WARNING [step standard_pgap] completed permanentFail
[2023-03-14 08:53:48] INFO [workflow ] completed permanentFail
[2023-03-14 08:53:48] DEBUG [workflow ] outputs {

**Comment by azat-badretdin** [comment]
Thank you. This is informative. 

The Python conflict happens _inside_ docker image when we are trying to run third party CheckM with the python that we have inside. 

Not sure how this could have happened

Could you please post the beginning of your `cwltool.log` output, the part that contains calling command lines and system information? Thanks

**Comment by dlhuseby29** [comment]
That's great that we're getting somewhere.

Here is the beginning of the cwltool.log:

Original command: ./pgap.py -r -o mg37_results /Users/diarmaid3/.pgap/test_genomes/MG37/input.yaml

Docker command: /usr/local/bin/docker run -i --rm --user 501:20 --volume /Users/diarmaid3/.pgap/input-2022-12-13.build6494:/pgap/input:ro,z --volume /Users/diarmaid3/.pgap/test_genomes/MG37:/pgap/user_input:z --volume /Users/diarmaid3/.pgap/test_genomes/MG37/pgap_input_5sw59dcb.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /var/folders/bt/2j865c0d6zjghn_t1kc01_280000gn/T/:/tmp:rw,z --volume /Users/diarmaid3/Desktop/Annotation_Queue/mg37_results.12:/pgap/output:rw,z ncbi/pgap:2022-12-13.build6494 cwltool --timestamps --debug --disable-color --preserve-entire-environment --outdir /pgap/output pgap/pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
  class: File
  location: ASM2732v1.annotation.nucleotide.1.fasta
submol:
  class: File
  location: pgap_submol_29p_il51.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---

--- Start Runtime Report ---
{
    "CPU cores": 12,
    "Docker image": "ncbi/pgap:2022-12-13.build6494",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq dtes64 ds_cpl ssse3 cx16 xtpr pcid dca sse4_1 sse4_2 popcnt aes hypervisor lahf_lm arat",
    "cpu model": "Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz",
    "max user processes": "unlimited",
    "memory (GiB)": 47.1,
    "memory per CPU core (GiB)": 3.9,
    "open files": 1048576,
    "tmp disk space (GiB)": 195.4,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 306.6
}
--- End Runtime Report ---

[2023-03-14 07:47:12] INFO /root/venv/bin/cwltool 3.1.20221201130942
[2023-03-14 07:47:12] INFO Resolved 'pgap/pgap.cwl' to 'file:///pgap/pgap/pgap.cwl'
pgap/pgap.cwl:22:7: Warning: Field `location` contains undefined reference to
                    `file:///pgap/pgap/input`
[2023-03-14 07:47:51] DEBUG [workflow ] initialized from file:///pgap/pgap/pgap.cwl
[2023-03-14 07:47:51] INFO [workflow ] start
[2023-03-14 07:47:51] DEBUG [workflow ] inputs {
    "fasta": {
        "class": "File",
        "location": "file:///pgap/user_input/ASM2732v1.annotation.nucleotide.1.fasta",
        "size": 588482,
        "basename": "ASM2732v1.annotation.nucleotide.1.fasta",
        "nameroot": "ASM2732v1.annotation.nucleotide.1",
        "nameext": ".fasta"
    },

**Comment by azat-badretdin** [comment]
Thanks, that is helpful

> Intel(R) Xeon(R) CPU E5645 @ 2.40GHz

Are you running this under Ubuntu or some other Linux distro for PCs or MSL 2 under Windows?

**Comment by dlhuseby29** [comment]
This is running on a Mac Pro:

Model Name:	Mac Pro
  Model Identifier:	MacPro5,1
  Processor Name:	6-Core Intel Xeon
  Processor Speed:	2.4 GHz
  Number of Processors:	2
  Total Number of Cores:	12
  L2 Cache (per Core):	256 KB
  L3 Cache (per Processor):	12 MB
  Memory:	64 GB

Though we have tried it also on another newer Mac Pro, for what it is worth:

Model Name:	Mac Pro
  Model Identifier:	MacPro6,1
  Processor Name:	12-Core Intel Xeon E5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	12
  L2 Cache (per Core):	256 KB
  L3 Cache:	30 MB
  Hyper-Threading Technology:	Enabled
  Memory:	64 GB

**Comment by dlhuseby29** [comment]
Ran it again and this time we got the .gbk file in addition to the .gff and other files.

Seems strange that there should apparently be some randomness in the results files that we get out each time.

Here were the output files for 3 consecutive runs of the test genome. Only difference in the input was that the first one was run with the --debug flag.

![Run 1](https://user-images.githubusercontent.com/115994272/224983196-d5d55680-10fb-4c24-8f15-258b1d310d07.png)
![Run 2](https://user-images.githubusercontent.com/115994272/224983214-70e8494d-bec3-451d-887b-045d0d12ff01.png)
![Run 3](https://user-images.githubusercontent.com/115994272/224983231-73333172-bb37-495f-99c4-f7d11f88de2b.png)

**Comment by azat-badretdin** [comment]
Could be memory related. Would you like to try it with `--cpus 1` switch?

**Comment by dlhuseby29** [comment]
With the --cpus 1 flag, it fails in exactly the same way.

One idea we had was to roll back to the previous version that worked for us. Not an entirely satisfying solution, but maybe one that could allow us to annotate again.

Or, as you said, could it be that everything is 'working' in the sense that we are generating annotations? Is there any reason why these annotations would be suspicious --or importantly, un-submit-able to NCBI?

**Comment by dlhuseby29** [comment]
So I guess we will handle this by ignoring the errors if the .gbk file is generated?

We did run it last night again on one our actual genomes that we wish to annotate and it didn't manage to generate the .gbk file. In this case I guess we run it again a few times and see if it can complete it. 

I have been worried that the problem is this specific system because it cannot be upgraded past OS 10.13 because of the age of the computer. We have run it a few times on a similar, but newer system currently running OS 12.6.3 and a newer version of Docker. We checked the logs and this computer generates an error log that seems extremely similar to the one on the older system. This makes me suspect that this could be a general Mac problem. I saw in the notes that you cannot be certain that this will work on Mac systems at all, so maybe this is a situation where we have encountered an incompatibility.

**Comment by azat-badretdin** [comment]
Thank you for this information! 

These seem all valid concerns to me.

**Comment by dlhuseby29** [comment]
I can add to this that after running the pipeline a few dozen times we have a success rate of generating the .gbk file at the end of the process of about 50%.

**Comment by george-coulouris** [comment]
@dlhuseby29, thanks for reporting. I believe I was able to reproduce this issue, we'll take a look.

**Comment by george-coulouris** [comment]
I can no longer reproduce this issue.
