### ISSUE TITLE
[BUG] PGAP fails install when running on singularity.

### ISSUE THREAD

**Issue by Ge0rges** [ncbi/pgap#272]
Running on Rocky Linux. Installed successfully by doing `pgap.py --update -D /Accounts/gkanaan/.conda/envs/methylate/bin/singularity` as my system does not support docker.

I then run PGAP by doing `pgap.py --container-path /researchdrive/gkanaan/tools/pgap/pgap_2023-10-03.build7061.sif -D /Accounts/gkanaan/.conda/envs/methylate/bin/singularity -r -o annotation/$genome_name/ -g $genome -s $genome_name --taxcheck --auto-correct-tax`

I get the following error and output:

```
PGAP version 2023-10-03.build7061 is up to date.
installation directory: /Accounts/gkanaan/.pgap
Sys. de fichiers              blocs de 1K     Utilisé Disponible Uti% Monté sur
137.22.86.56:/liverpool_users 20401094656 13224792576 7176302080  65% /Accounts
Skipping already installed tarball: https://s3.amazonaws.com/pgap/input-2023-10-03.build7061.tgz
Downloading and extracting tarball: https://s3.amazonaws.com/pgap/input-2023-10-03.build7061.ani.tgz
Downloading (as needed) Docker image docker:///researchdrive/gkanaan/tools/pgap/pgap_2023-10-03.build7061.sif
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker:///researchdrive/gkanaan/tools/pgap/pgap_2023-10-03.build7061.sif: unable to parse image name docker:///researchdrive/gkanaan/tools/pgap/pgap_2023-10-03.build7061.sif: invalid reference format
None
Traceback (most recent call last):926 bytes (100.00%)
  File "/researchdrive/gkanaan/tools/pgap/pgap.py", line 1067, in <module>
    main()
  File "/researchdrive/gkanaan/tools/pgap/pgap.py", line 994, in main
    params = Setup(args)
  File "/researchdrive/gkanaan/tools/pgap/pgap.py", line 558, in __init__
    self.update()
  File "/researchdrive/gkanaan/tools/pgap/pgap.py", line 718, in update
    raise Exception(f'installation of some or all of components failed. Please remove {self.data_path}, {self.install_dir}/test_genomes, {self.test_genomes_path} directories and try again.')
Exception: installation of some or all of components failed. Please remove /Accounts/gkanaan/.pgap/input-2023-10-03.build7061, /Accounts/gkanaan/.pgap/test_genomes, /Accounts/gkanaan/.pgap/test_genomes-2023-10-03.build7061 directories and try again.
```

**Comment by azat-badretdin** [comment]
Thank you, Gio, for your report! This looks like something specific happens on your computer system related to singularity setup. 

What is the version of singularity you are using?

**Comment by Ge0rges** [comment]
It seems like removing the --container-path argument fixed it.
