### ISSUE TITLE
[BUG] Fail in GenBank output file

### ISSUE THREAD

**Issue by juansebe1** [ncbi/pgap#296]
Why does pgap does not give me the GenBank (.gb) file in the output?

**Comment by azat-badretdin** [comment]
Thank you for your report, user @juansebe1 !

Do you have a file with .gbk extension? If not, could you please provide details of your run, if the file `cwltool.log` contains `permanentFail` and 100 lines of log preceding the first `permanentFail` in this log file?

**Comment by juansebe1** [comment]
No, I don't have a .gbk file
Can I share you the cwltool.log file and see what you are asking ?
Yes, it contains permanentFail

[cwltool.log.zip](https://github.com/ncbi/pgap/files/15009572/cwltool.log.zip)

**Comment by azat-badretdin** [comment]
For the record, this is the relevant part:

```

+ /root/venv/bin/checkm taxonomy_wf -t 1 -g -x fa domain Bacteria bins-prot/ taxonomy_wf-prot/
Process SyncManager-1:
Traceback (most recent call last):
  File "/opt/python-3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/managers.py", line 583, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/managers.py", line 156, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/root/venv/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/root/venv/lib/python3.9/site-packages/checkm/main.py", line 992, in parseOptions
    self.analyze(options)
  File "/root/venv/lib/python3.9/site-packages/checkm/main.py", line 326, in analyze
    binIdToModels = mgf.find(binFiles,
  File "/root/venv/lib/python3.9/site-packages/checkm/markerGeneFinder.py", line 68, in find
    binIdToModels = mp.Manager().dict()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/python-3.9/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

```

**Comment by azat-badretdin** [comment]
This looks similar to the issue #276 and judging by the user host mounted dirs, this is also a Mac system.

Issue #276 was closed as de facto unresolved, the user did not reply for two months.

**Comment by azat-badretdin** [comment]
As you can see I labeled this Issue with our internal ticket created based on #276 

Someone from our team will have a look.

Thank you for your patience!

**Comment by juansebe1** [comment]
Hi
Yes, it is a Mac system.
I'll take a look at https://github.com/ncbi/pgap/issues/276 and wait for the response of your team, 
Thanks!

**Comment by juansebe1** [comment]
Hi! I've tried again with the same genome and with another from the GenBank, and I could not obtain a .gbk file neither. 
I'll share with you the cwltool.log file and the genome in .fasta extension, so if you can see what I'm doing wrong, 

thank you
[cwltool.log.zip](https://github.com/ncbi/pgap/files/15148421/cwltool.log.zip)
[fle_am.fasta.zip](https://github.com/ncbi/pgap/files/15148439/fle_am.fasta.zip)

**Comment by azat-badretdin** [comment]
Thank you for adding new data, user @juansebe1 ! This is very helpful!

**Comment by azat-badretdin** [comment]
Unfortunately, we have not been able to reproduce this error on our end
