### ISSUE TITLE
[BUG] <title> installation failed

### ISSUE THREAD

**Issue by BlackMonolith** [ncbi/pgap#319]
**Describe the bug**
i want to install the latest version of pgap in my ubuntu machine，i use ./pgap.py --update to download the database . The download progress worked well. However, when the download progress reaches 100%, an error occured.

**Software versions (please complete the following information):**
 - OS: Ubuntu 24.04
 - The latest version of PGAP is 2024-07-18.build7555, you have nothing installed locally.
 - Docker version 27.2.0, build 3ab4256

**Log Files**
```
Traceback (most recent call last):123 bytes (100.00%)
  File "/home/ihbmmb/software/pgap/pgap.py", line 1123, in main
    params = Setup(args)
             ^^^^^^^^^^^
  File "/home/ihbmmb/software/pgap/pgap.py", line 630, in __init__
    self.update()
  File "/home/ihbmmb/software/pgap/pgap.py", line 782, in update
    raise Exception(f'installation of some or all of components failed. Please remove {self.data_path}, {self.install_dir}/test_genomes, {self.test_genomes_path} directories and try again.')
Exception: installation of some or all of components failed. Please remove /home/ihbmmb/Data/Database/pgapdb//input-2024-07-18.build7555, /home/ihbmmb/Data/Database/pgapdb//test_genomes, /home/ihbmmb/Data/Database/pgapdb//test_genomes-2024-07-18.build7555 directories and try again.
```

**Additional context**
I have tried many times, such as completely clearing the database and downloading again, but this problem still persists

**Comment by azat-badretdin** [comment]
Thank you for your report, user @BlackMonolith !

> The download progress worked well. However, when the download progress reaches 100%, 

Could you please redirect the output of your command `<your command> &> a.log` and post here `a.log`? Thanks!

**Comment by BlackMonolith** [comment]
Thank you for the response！
I run the command `./pgap.py --update &> a.log`, the problem didn't occur again. My PGAP works well now and the database is up to date.
![image](https://github.com/user-attachments/assets/aabeec47-13f6-487e-b5ee-e4abaa9c615b)

**Comment by azat-badretdin** [comment]
Glad to hear that, user @BlackMonolith ! I hope our software works for you like a rock :-)
